title: Chlog
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: ""
url: "https://c4stleb.github.io/"
site-twitter: 

# Author Settings
author: Chung Jeon 
author-img: profile.jpg 
about-author: I am an infra engineer focusing on Cloud service. Always hungry to keep learning. 
social-instagram: blue_pot91
social-github: c4stleb 
social-linkedin: chung-jeon-973a3b161 
social-email: ichung91@naver.com 

# Disqus
discus-identifier: c4stleb 

# Tracker
# Google Analytics
analytics: UA-165591370-1 

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
