title: Chlog
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: ""
url: "https://c4stleb.github.io/"
site-twitter: 

# Author Settings
author: Chung Jeon 
author-img: profile.jpg 
about-author: I am a infra engineer focusing on devops. Always hungry to keep learning. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: c4stleb # add your Github handle
social-linkedin: https://www.linkedin.com/in/chung-jeon-973a3b161/ # add your Linkedin handle
social-email: ichung91@naver.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
